Add hybrid card support
mercadopago/px-ios pull request #2378
Opened 2020-12-14 13:24 UTC by jscaramal-meli

##  Cambios introducidos : 
- Se creó la clase HybridAMCard que representa la tarjeta híbrida
- Se parsean los campos card_type, color, gradient_colors y payment_method_image_URL en display_info para las tarjetas de AccountMoney
- Se muestra un modal para el behaviour de tap_card aunque el medio no esté suspendido para que sea posible mostrar el modal de tarjeta híbrida

2020-12-14 19:35 UTC, ericertlMELI requested changes

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
> +                let cardUI : CardUI = accountMoney.cardType == .defaultType ? AccountMoneyCard(isDisabled: targetNode.status.isDisabled(), cardLogoImageUrl: accountMoney.paymentMethodImageURL, color:
Esto queda poco legible al ser tan largo. Desglosalo tipo:

```
let isDefaultCardType = accountMoney.cardType == .defaultType
                let isDisabled = targetNode.status.isDisabled()
                let cardLogoImageUrl = accountMoney.paymentMethodImageURL
                let color = accountMoney.color
                let gradientColors = accountMoney.gradientColors
                let cardUI: CardUI = isDefaultCardType ?
                    AccountMoneyCard(isDisabled: isDisabled, cardLogoImageUrl: cardLogoImageUrl, color: color, gradientColors: gradientColors) :
                    HybridAMCard(isDisabled: isDisabled, cardLogoImageUrl: cardLogoImageUrl, color: color, gradientColors: gradientColors)
```

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/AccountMoneyCard.swift
> +        guard let imageURL = self.cardLogoImageUrl, imageURL.isNotEmpty else {
Para que queres saber si tiene `imageURL` si despues nolo vas a usar? Y si no lo tiene no muestra ni siquiera el logo que hay en los recursos locales. Me parece que esta mal

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/HybridAMCard.swift
> +        guard let imageURL = self.cardLogoImageUrl, imageURL.isNotEmpty else {
Lo mismo que la anterior. No se para que buscas si imageURL existe y no esta vacio para mostrar una imagen local

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
> +    func renderHybridAMCard(cardUI: HybridAMCard, isDisabled: Bool, cardSize: CGSize, bottomMessage: PXCardBottomMessage? = nil, accessibilityData: AccessibilityCardData) {
Esto hace exactamente lo mismo que la func renderAccountMoneyCard.
Crea una sola func para los 2 casos para evitar duplicar codigo.

```
func renderAccountMoneyORHybridCard(cardUI: CustomCardDrawerUI, isDisabled: Bool, cardSize: CGSize, bottomMessage: PXCardBottomMessage? = nil, accessibilityData: AccessibilityCardData) {
        
        containerView.layer.masksToBounds = false
        containerView.backgroundColor = .clear
        containerView.removeAllSubviews()
        containerView.layer.cornerRadius = cornerRadius
        cardHeader = MLCardDrawerController(cardUI, PXCardDataFactory(), isDisabled)
        cardHeader?.view.frame = CGRect(origin: CGPoint.zero, size: cardSize)
        cardHeader?.animated(false)
        cardHeader?.show()

        if let headerView = cardHeader?.view {
            containerView.addSubview(headerView)
            if let hybridCard = cardUI as? HybridAMCard {
                hybridCard.render(containerView: containerView, isDisabled: isDisabled, size: cardSize)
            } else if let amCard = cardUI as? AccountMoneyCard {
                amCard.render(containerView: containerView, isDisabled: isDisabled, size: cardSize)
            }
            PXLayout.centerHorizontally(view: headerView).isActive = true
            PXLayout.centerVertically(view: headerView).isActive = true
        }

        addBottomMessageView(message: bottomMessage)
        accessibilityLabel = getAccessibilityMessage(accessibilityData)
    }
```

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
>                  if targetModel.cardUI is AccountMoneyCard {
Nunca uses force unwrap

```
if let customCardDrawerUI = targetModel.cardUI as? AccountMoneyCard {
                    // AM card.
                    cell.renderAccountMoneyORHybridCard(cardUI: customCardDrawerUI, isDisabled: targetModel.status.isDisabled(), cardSize: pagerView.itemSize, bottomMessage: bottomMessage, accessibilityData: accessibilityData)
                } else if let customCardDrawerUI = targetModel.cardUI as? HybridAMCard {
                    // Hybrid AM card
                    cell.renderAccountMoneyORHybridCard(cardUI: customCardDrawerUI, isDisabled: targetModel.status.isDisabled(), cardSize: pagerView.itemSize, bottomMessage: bottomMessage, accessibilityData: accessibilityData)
```

2020-12-14 19:35 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
>      func flipToBack() {
`flipToBack()` y `flipToFront()` no se usa, podes matarlas

2020-12-14 20:05 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/AccountMoneyCard.swift
> +        guard let imageURL = self.cardLogoImageUrl, imageURL.isNotEmpty else {
Acá, si hay imageURL, no hago nada, porque la clase padre ya renderiza el icono si está la URL, caso contrario, utilizo el asset por defecto.

2020-12-14 20:06 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/HybridAMCard.swift
> +        guard let imageURL = self.cardLogoImageUrl, imageURL.isNotEmpty else {
Acá, si hay imageURL, no hago nada, porque la clase padre ya renderiza el icono si está la URL, caso contrario, utilizo el asset por defecto.

2020-12-14 20:25 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
>                  if targetModel.cardUI is AccountMoneyCard {
En este caso no sería un force unwrapping porque el value de cardUI no es optional. Por lo que estuve viendo el operador "is" devuelve si el objeto es de una clase o conforma un protocolo, pero no genera runtime errors si no fuera el caso, simplemente no entra en el if.

2020-12-14 20:25 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
>      func flipToBack() {
Ok, las elimino!

2020-12-14 20:28 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
> +        } else if let selectedCard = selectedCard {
Ahí lo que permitimos es, si quieren ponerle desde back, sea híbrida o no, un modal al tapear, que puedan hacerlo. Quedó así porque selectedCard es un optional. Quizá lo que se podría hacer es quitar lo de si es suspended, porque llegado el caso si queremos permitir que todas las tarjetas que tienen un behaviour sean tappeables creo que no tiene sentido ponerse a ver si están suspendidas o no...

2020-12-14 20:30 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
> +                let cardUI : CardUI = accountMoney.cardType == .defaultType ? AccountMoneyCard(isDisabled: targetNode.status.isDisabled(), cardLogoImageUrl: accountMoney.paymentMethodImageURL, color:
Es verdad, es una línea demasiado larga. Queda bueno eso.

2020-12-14 20:45 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
> +        } else if let selectedCard = selectedCard {
Viendo lo de cardTapped me genera una duda, eso se ejecuta cuando se toca el botoncito info si hay installments? Estaría bien que también se abra el modal en ese caso? Asumo que sí...

2020-12-14 20:48 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
> +        } else if let selectedCard = selectedCard {
Viendo nuevamente lo de arriba, creo que está bien en ese orden, primero se pregunta si es suspended, en caso que no, se pregunta si está disabled, y por último si hay alguna card selected. Si junto los criterios de Suspended or Hybrid en una sola función, primaría el modal de backend por sobre el de disabled y creo que no estaría bien. Independientemente de que la tarjeta híbrida traiga un modal que indica que "ahora es negra", debería ser más importante para el user saber que está deshabilitada en caso que así sea.

2020-12-15 12:27 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
> +    func renderHybridAMCard(cardUI: HybridAMCard, isDisabled: Bool, cardSize: CGSize, bottomMessage: PXCardBottomMessage? = nil, accessibilityData: AccessibilityCardData) {
Está bueno. Lo implemento.

2020-12-15 13:23 UTC, ericertlMELI requested changes

2020-12-15 13:23 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
>                  if targetModel.cardUI is AccountMoneyCard {
Tenes razon, no es un force unwrap, es un force cast. De cualquier manera, queda mas prolijo de la manera que te comente, ya que no estas preguntando si es de un tipo especifico y despues casteandolo, sino que ya lo casteas en el if

2020-12-15 13:23 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/HybridAMCard.swift
> +        guard let imageURL = self.cardLogoImageUrl, imageURL.isNotEmpty else {
Ok, me confundi el guard con un if

2020-12-15 13:23 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
> +        } else if let selectedCard = selectedCard {
Habria que validar como esta en Android. Asi como esta ahora no se ve muy bien

2020-12-16 15:18 UTC, ericertlMELI approved these changes
Joya!!

2020-12-16 17:53 UTC, merged