feat: Showing switch for combo cards
mercadopago/px-ios pull request #2397
Opened 2021-02-08 15:48 UTC by jscaramal-meli

##  Cambios introducidos : 
- Se muestra el switch para tarjetas combo

2021-02-08 16:20 UTC, ericertlMELI requested changes

2021-02-08 16:20 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDisplayInfo.swift
> +    enum CodingKeys: String, CodingKey {
Si usas codable no hace falta este enum si pasas de snakecase a camelcase.

2021-02-08 16:20 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
> +import MLCardDrawer
en vez de importar cardrawer aca, modifica el render de `PXCardSliderPagerCell` para recibir `targetModel.displayInfo?.switchInfo` y agrega el codigo de mas abajo en esa func de render

2021-02-08 16:20 UTC, ericertlMELI commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
> +    public var cardHeader: MLCardDrawerController?
haciendo el cambio de mas arriba, podes volver a poner esto como privado

2021-02-09 12:16 UTC, jscaramal-meli commented on MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDisplayInfo.swift
> +    enum CodingKeys: String, CodingKey {
Ah buena data, en este caso lo saqué de PXOneTapDto y ya estaba definido, lo que sí, agregué `case switchInfo = "switch"` por el hecho de que switch sea una palabra reservada.

2021-02-09 13:07 UTC, ericertlMELI approved these changes
Joya, quedo mucho mas prolijo. Lo unico que haria mas adelante es tratar de unificar codigo duplicado en PXCardSliderPagerCell.swift (lo del cardHeader y switchInfo tener una func reutilizable para tarjeta normal y account money)
Groso Jona

2021-02-09 13:15 UTC, merged