[Feature][PXN-2755] Adding post payment flow support
mercadopago/px-ios pull request #2613
Opened 2021-12-27 18:20 UTC by rgrajalesmeli

## What have changed?
Adding post payment flow support that will allow integrators to interrupt the PX flow right before displaying the congrats and launching a new flow on their end to go back to the PX flow after executing whatever they need to and finally displaying the congrats screen 

## How to test:
To use this new feature the integrator must to setup the `PXPostPaymentConfiguration` and suscribe to a notification so they can be notified of a successful payment, this way:
```MercadoPagoCheckout.NotificationCenter.SubscribeTo.postPaymentAction(
            forName: postPaymentConfig.postPaymentNotificationName ?? .init("")
        ) { resultBlock in
            print("Got the notification")
            let postPayment = PostPaymentViewController(with: resultBlock)

            self.present(
                UINavigationController(rootViewController: postPayment),
                animated: true,
                completion: nil
            )
        }
```

## Prints for layout changes:
| Success Payment - Success Accreditation | Success Payment - Accreditation Error | Failed Payment
|:-:|:-:|:-:|
| ![Success_Payment_Acreditation](https://user-images.githubusercontent.com/87155841/147496540-f9001500-44d0-4f1b-869a-d715f9d73a24.gif) | ![Success_Payment_Acreditation_Error](https://user-images.githubusercontent.com/87155841/147496563-eb0bd5a3-427b-48b4-93fe-9a282da4af1c.gif) | ![Failed_Payment](https://user-images.githubusercontent.com/87155841/147496570-d80dd3fb-c78a-4e00-9679-5c026b4f1ef3.gif)

## Extras:
Tests passed successfully:
| Tests |
|:-:|
| <img width="368" alt="Captura de Pantalla 2021-12-27 a la(s) 1 06 17 p  m" src="https://user-images.githubusercontent.com/87155841/147496771-61cacd11-4cb1-413c-9872-05abcde8fa3a.png"> |

2021-12-28 18:15 UTC, jlainog-meli approved these changes

2021-12-28 18:25 UTC, Esteban-ML approved these changes

2021-12-28 18:25 UTC, Esteban-ML commented on ExampleSwift/ExampleSwift/Controllers/CustomCheckoutWithPostPaymentViewController.swift
> +    @IBAction private func iniciarCheckout(_ sender: Any) {
Is there any reason for this being in spanish?

2021-12-28 18:25 UTC, Esteban-ML commented on ExampleSwift/ExampleSwift/Controllers/CustomCheckoutWithPostPaymentViewController.swift
> +    @IBAction private func restablecerDatos(_ sender: Any) {
Same as above

2021-12-28 19:11 UTC, ALEJOVILLA-ML reviewed
Just a few comments

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/Config/PXPostPaymentConfiguration.swift
> +open class PXPostPaymentConfiguration: NSObject {
why open? does our clients need to inherit from it?

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +internal extension MercadoPagoCheckout.NotificationCenter.PublishTo {
is it required to explicitly say "internal"

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
> +                animatedView.transform = CGAffineTransform(scaleX: 50, y: 50)
take this to a constant

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
> +            UIView.animate(withDuration: 0.5, animations: {
move to a constants enum

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
>              let scaleFactor: CGFloat = 0.40
move to a constants enum

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
can we split this conditionals into separate files? it would be easier to understand

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +            let resultBlock = $0.object as! MercadoPagoCheckout.PostPayment.ResultBlock
remove force unwrap

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +    private var testCase: CustomCheckoutTestCase
this can be let instead of var since you're getting the value from the init func

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0, execute: { [self] in
take this 5.0 value to a constants enum

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        return nil
does it always returns nil?

2021-12-28 19:11 UTC, ALEJOVILLA-ML commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        return true
does it always returns true?

2021-12-28 19:22 UTC, rgrajalesmeli commented on ExampleSwift/ExampleSwift/Controllers/CustomCheckoutWithPostPaymentViewController.swift
> +    @IBAction private func iniciarCheckout(_ sender: Any) {
No reason we copied that part of the code from the existing one and didn’t realized of the Spanish name, will change it 👍

2021-12-28 19:22 UTC, rgrajalesmeli commented on ExampleSwift/ExampleSwift/Controllers/CustomCheckoutWithPostPaymentViewController.swift
> +    @IBAction private func restablecerDatos(_ sender: Any) {
same as above

2021-12-28 19:30 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/Config/PXPostPaymentConfiguration.swift
> +open class PXPostPaymentConfiguration: NSObject {
That’s correct, clients may need to inherit from it like the other configurations for the checkout builder

2021-12-28 19:31 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +internal extension MercadoPagoCheckout.NotificationCenter.PublishTo {
i don’t think so, will remove it

2021-12-28 19:33 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
> +                animatedView.transform = CGAffineTransform(scaleX: 50, y: 50)
We don’t want to spend too much time refactoring legacy ui code, so i'll add the constants enum for the changes we made only. The other places in the `PXAnimatedButton`  class that may apply to this refactor will have to wait for now

2021-12-28 19:34 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
> +            UIView.animate(withDuration: 0.5, animations: {
same as above

2021-12-28 19:34 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
>              let scaleFactor: CGFloat = 0.40
same as above

2021-12-28 19:35 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
not sure following you with this comment, what do you mean with a different file for a conditional?

2021-12-28 19:36 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +            let resultBlock = $0.object as! MercadoPagoCheckout.PostPayment.ResultBlock
sure

2021-12-28 19:37 UTC, rgrajalesmeli commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0, execute: { [self] in
this is used for a very specific use case in the test app, since we won’t be adding anything else to the constants enum at this moment i don’t think it would be necessary, at the end this `5.0` will be only used here

2021-12-28 19:40 UTC, rgrajalesmeli commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        return nil
it does for this use case, this function must to be implemented due to the `PXPaymentProcessor` protocol, it's saying basically that we won’t be using a custom visual processor, instead we will be using the one defined by the checkout

2021-12-28 19:42 UTC, rgrajalesmeli commented on ExampleSwift/ExampleSwift/Helpers/CustomPostPaymentProcessor.swift
> +        return true
it does due to the `PXPaymentProcessor` protocol, this time the `true` value is indicating the the custom processor will be supporting the payment, it could have a better name but that’s what we have today and we don’t want to break something for other integrators

2021-12-28 20:10 UTC, ALEJOVILLA-ML approved these changes
Awesome work, great PR!

2021-12-28 20:37 UTC, ricardo-dalambert-meli requested changes

2021-12-28 20:37 UTC, ricardo-dalambert-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +        NotificationCenter.default.post(name: aName, object: result, userInfo: nil)
Why notification pattern here? 

I personally believe that delegate pattern is far more resilient that notifications for inter-component communication purposes. We don't know who's listening at execution time and if a particular instance register itself to listen `aName` notification forgot to unsubscribe itself after it, this notification can end up in several undesired places at the same time, creating potential undesired behaviors.

2021-12-28 20:37 UTC, ricardo-dalambert-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
i also believe that `== true` here is redundant, since the return of `self.businessResult?.isApproved()` is boolean anyway, but the fact that `businessResult` and `paymentResult` are both optionals can create strange behaviors on this boolean expression when one of then is `nil`. Maybe, as a suggestion, this approach can be more resilient:

```
func shouldNavigateToPostPaymentFlow() -> Bool {
        guard let businessResult = self.businessResult,
              let paymentResult = self.paymentResult else { return false }
        
        return self.postPaymentNotificationName != nil &&
        (businessResult.isApproved() || paymentResult.isApproved())
    }
```

2021-12-28 20:37 UTC, ricardo-dalambert-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift
> +            PXAnimatedButton.animateButtonWith(status: status, statusDetail: statusDetail, explode: !shouldNotExplode)
this is confusing to me: `shouldNotExplode` is the opposite of `shouldExplode`, and on the next line you declared `explode: !shoudNotExplode`? Maybe to make it clearer, we can declare this way:

```
let shouldExplode = !(model.hasPostPaymentFlow && PXPaymentStatus(rawValue: status) == .APPROVED)
PXAnimatedButton.animateButtonWith(status: status, statusDetail: statusDetail, explode: shouldExplode)
```

2021-12-29 14:44 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
the operator `==` has an overload for optionals that does that exact thing so by doing  `optional == true` it is the same as `optional == .some(true)` and avoid the need to unwrap the optional before validate the condition.

2021-12-29 14:52 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +        NotificationCenter.default.post(name: aName, object: result, userInfo: nil)
By using a separate NotificationCenter and by exposing the subscription to it only using the method in the `SubscribeTo` it mitigates the risk of undesired places listening to unexpected notifications.
```swift
extension MercadoPagoCheckout {
    public enum NotificationCenter {
        static let `default` = Foundation.NotificationCenter()
```

2021-12-29 15:40 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +        NotificationCenter.default.post(name: aName, object: result, userInfo: nil)
In addition, we added this approach in order to behave in a similar way to android and have a common solution between both platforms providing a configuration to the integrators where they can wait for us to take the control over the PX flow and then setting a result whenever they need us to take the control again

2021-12-29 17:40 UTC, ricardo-dalambert-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
ok, perfect. 1x0 :)

2021-12-29 17:59 UTC, ricardo-dalambert-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout+NotificationManager.swift
> +        NotificationCenter.default.post(name: aName, object: result, userInfo: nil)
All right. but who exactly in this extensions is responsible for the job of avoiding that the same exposed object register itself again without subscribing first? Assuming that this specific NotificationCenter is static...

On the example app itself, there is just a single reference for `SubscribeTo.`, but none for `UnsubscribeTo`. This could be the scenario.

2021-12-29 21:18 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
I think @ALEJOVILLA-ML means something like this
```swift
let hasPostPaymentFlow = self.postPaymentNotificationName != nil
let isResultApproved = self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true
return hasPostPaymentFlow && isResultApproved
```

2021-12-29 21:54 UTC, ALEJOVILLA-ML commented on MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
> +        return self.postPaymentNotificationName != nil && (self.businessResult?.isApproved() == true || self.paymentResult?.isApproved() == true)
yeah sorry my bad i got confused, different lines, not files lol

2022-01-03 20:22 UTC, ALEJOVILLA-ML approved these changes
LG! great work

2022-01-04 21:50 UTC, jlainog-meli approved these changes

2022-01-04 21:50 UTC, merged