Correção do bug PXN-1550 - Total deve aparecer sem desconto na tela p…
mercadopago/px-ios pull request #2680
Opened 2022-03-02 13:00 UTC by rafaelagaldino2703

…ara adicionar novo cartão.

## What have changed?

## How to test:

## Prints for layout changes:

## Extras:

2022-03-02 15:47 UTC, LucasCarvalho00 approved these changes

2022-03-03 16:20 UTC, matheusctMeli requested changes

2022-03-03 16:20 UTC, matheusctMeli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift
> +                                         isTotal: haveDiscount ? true : false,
haveDiscount ja é bool precisa mesmo desse ternario? não poderia ser só o proprio valor dele?

2022-03-03 16:57 UTC, rafaelagaldino2703 commented on MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift
> +                                         isTotal: haveDiscount ? true : false,
sim, pode ser apenas o valor dele, não faz sentido esse ternário. 

alteração feita.

2022-03-03 18:55 UTC, matheusctMeli approved these changes

2022-03-04 12:49 UTC, matheusctMeli approved these changes

2022-03-04 19:14 UTC, LucasCarvalho00 approved these changes

2022-03-07 12:46 UTC, pesilsa approved these changes

2022-03-07 12:55 UTC, matheusctMeli approved these changes

2022-03-09 20:02 UTC, merged