Adding primary_action and secondary_action tracks to Congrats Screen
mercadopago/px-ios pull request #2717
Opened 2022-04-12 19:38 UTC by ALEJOVILLA-ML

## What have changed?
Adding primary_action and secondary_action tracks to Congrats Screen

## How to test:

## Prints for layout changes:

## Extras:

2022-04-12 19:39 UTC, Esteban-ML commented on ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
> +				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/PureLayout.framework",
@jlainog  This PR is adding the PureLayout.framework removed in the PR I made before, I don't really understand why the bundle exec pod install behaves this way...

Should we keep it, right?

2022-04-12 19:39 UTC, Esteban-ML reviewed
LG! 🦦

2022-04-12 19:39 UTC, Esteban-ML approved these changes

2022-04-13 12:52 UTC, jlainog-meli commented on ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
> +				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/PureLayout.framework",
we should try removing it explicitly just to make sure we are using it... if not we remove it completely.

2022-04-13 12:55 UTC, jlainog-meli requested changes
LG but I think there is an error when intercepting the actions

2022-04-13 12:55 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
> +        paymentCongrats.mainAction?.action = action
looks like you are configuring the same `mainAction.action` for both main and secondary action...

2022-04-13 17:41 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Core/PXAction.swift
> +        PXAction(label: self.label, action: {
cool, but remember to check the linter that was raising a warning here

2022-04-13 18:03 UTC, jlainog-meli approved these changes

2022-04-13 18:07 UTC, Esteban-ML approved these changes

2022-04-13 18:14 UTC, merged