(Changed)[PXN-4014] - Updating tracker and delete reason for tokenization error
mercadopago/px-ios pull request #2791
Opened 2022-06-13 12:42 UTC by rgrajalesmeli

## What have changed?
Updating tracker for tokenization error
Updating delete ESC reasons for tokenization error
Avoid deleting ESC when timeout or no internet error

## How to test:

## Prints for layout changes:

## Extras:

2022-06-13 15:36 UTC, jlainog-meli requested changes

2022-06-13 15:36 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/TokenizationFlow/TokenizationService.swift
> +                if let securityCode = savedESCCardToken.securityCode, securityCode.isNotEmpty {
this is already a condition so we can do 
`var shouldResetESC = savedESCCardToken.securityCode?.isNotEmpty == .some(true)`

2022-06-13 15:36 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Flows/TokenizationFlow/TokenizationService.swift
> +                default:
we can add a note here to point out what -1, and -2 means. because right now they are magic numbers to everyone.

2022-06-13 15:36 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/RequestLayer/Token/TokenService.swift
> +                completion(.failure(PXError(domain: ApiDomain.GET_TOKEN, error: error)))
great catch. we need to check the error screen that was depending on this to be hardcoded.

2022-06-13 15:36 UTC, jlainog-meli commented on MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Events.swift
> +    }
we can use this oportunity to change the signatures from functions to computed variables.

2022-06-13 23:16 UTC, rgrajalesmeli commented on MercadoPagoSDK/MercadoPagoSDK/RequestLayer/Token/TokenService.swift
> +                completion(.failure(PXError(domain: ApiDomain.GET_TOKEN, error: error)))
After reviewing this, i could validate it's only changing the copy and color for the error screen (snack-bar )
I think we need to check if it’s necessary to display always the same copy or color but i think we can addressing that in a different PR or ticket. 
@jlainog-meli

2022-06-13 23:26 UTC, jlainog-meli approved these changes

2022-06-14 03:46 UTC, rgrajalesmeli commented
rp retest

2022-06-14 19:58 UTC, Esteban-ML approved these changes

2022-06-14 20:21 UTC, merged